const uid="abcd1234";
var firstName="Angesh";
var lastName="G";
var emailId="abc@gmail.com";
var passWord="123456";
var confirmPassword="123456";
var countryName="India";
var stateName="TamilNadu";
var isLoggedinFromGoogle=false;
var isLoggedinFromFacebook=true;
console.log(`UNIQUE ID IS:${uid}
USER FIRSTNAME:${firstName}
USER LASTNAME:${lastName}
USER EMAILID:${emailId}
USER PASSWORD:${passWord}
USER CONFIRMPASSWORD:${confirmPassword}
USER COUNTRYNAME:${countryName}
USER STATENAME:${stateName}
USER ISLOGGEDINFROMGOOGLE:${isLoggedinFromGoogle}
USER ISLOGGEDINFROMFACEBOOK:${isLoggedinFromFacebook}`);